"""
Train a DeepONet baseline for the forward-operator pipe-flow dataset.

Goal
----
Learn the operator:

    R(z), fluid parameters, pressure drop, coordinate (z, eta) -> u(eta, z)

This is the first learning baseline for the forward-operator branch.

Input dataset
-------------
Generated by:

    python src/generate_forward_operator_dataset.py --n-samples 500

Expected file:

    data/forward_operator_dataset.npz

Run
---
Small test:

    python src/train_deeponet_forward.py --epochs 20

Main baseline:

    python src/train_deeponet_forward.py --epochs 500

Outputs
-------
models/deeponet_forward_baseline.pt
figures/deeponet_forward_training_loss.png
figures/deeponet_forward_prediction_example.png
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Tuple

import matplotlib.pyplot as plt
import numpy as np
import torch
from torch import nn


def get_device() -> torch.device:
    """Choose the best available PyTorch device."""
    if torch.backends.mps.is_available():
        return torch.device("mps")

    if torch.cuda.is_available():
        return torch.device("cuda")

    return torch.device("cpu")


def load_dataset(dataset_path: Path):
    """Load the generated forward-operator dataset."""
    if not dataset_path.exists():
        raise FileNotFoundError(
            f"Dataset not found: {dataset_path}\n"
            "Generate it first with:\n"
            "python src/generate_forward_operator_dataset.py --n-samples 500"
        )

    return np.load(dataset_path, allow_pickle=True)


def build_branch_features(data) -> np.ndarray:
    """
    Build branch input features.

    Branch input contains:
    - radius profile R(z)
    - pressure drop
    - viscosity, if Newtonian; otherwise 0
    - consistency K, if power-law; otherwise 0
    - flow index n, if power-law; otherwise 0
    - fluid code: 0 for Newtonian, 1 for power-law

    Shape:
        (n_samples, n_z + 5)
    """
    radius_profiles = data["radius_profiles"].astype(np.float32)
    pressure_drops = data["pressure_drops"].astype(np.float32)[:, None]

    viscosity = data["viscosity_values"].astype(np.float32)[:, None]
    consistency = data["consistency_values"].astype(np.float32)[:, None]
    flow_index = data["flow_index_values"].astype(np.float32)[:, None]
    fluid_code = data["fluid_codes"].astype(np.float32)[:, None]

    viscosity = np.nan_to_num(viscosity, nan=0.0)
    consistency = np.nan_to_num(consistency, nan=0.0)
    flow_index = np.nan_to_num(flow_index, nan=0.0)

    branch_features = np.concatenate(
        [
            radius_profiles,
            pressure_drops,
            viscosity,
            consistency,
            flow_index,
            fluid_code,
        ],
        axis=1,
    )

    return branch_features.astype(np.float32)


def train_val_split(
    n_samples: int,
    val_fraction: float,
    seed: int,
) -> Tuple[np.ndarray, np.ndarray]:
    """Create train/validation sample indices."""
    rng = np.random.default_rng(seed)
    indices = np.arange(n_samples)
    rng.shuffle(indices)

    n_val = max(1, int(val_fraction * n_samples))

    val_indices = indices[:n_val]
    train_indices = indices[n_val:]

    return train_indices, val_indices


class MLP(nn.Module):
    """Simple fully connected network."""

    def __init__(
        self,
        input_dim: int,
        output_dim: int,
        hidden_dim: int,
        n_layers: int,
    ):
        super().__init__()

        layers = []
        current_dim = input_dim

        for _ in range(n_layers):
            layers.append(nn.Linear(current_dim, hidden_dim))
            layers.append(nn.Tanh())
            current_dim = hidden_dim

        layers.append(nn.Linear(current_dim, output_dim))

        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Evaluate the MLP."""
        return self.net(x)


class DeepONet(nn.Module):
    """
    DeepONet model.

    branch input:
        full geometry and physical parameters

    trunk input:
        coordinate pair (z, eta)

    output:
        scalar velocity u(z, eta)
    """

    def __init__(
        self,
        branch_dim: int,
        trunk_dim: int = 2,
        latent_dim: int = 128,
        hidden_dim: int = 128,
        n_layers: int = 3,
    ):
        super().__init__()

        self.branch_net = MLP(
            input_dim=branch_dim,
            output_dim=latent_dim,
            hidden_dim=hidden_dim,
            n_layers=n_layers,
        )

        self.trunk_net = MLP(
            input_dim=trunk_dim,
            output_dim=latent_dim,
            hidden_dim=hidden_dim,
            n_layers=n_layers,
        )

        self.bias = nn.Parameter(torch.zeros(1))

    def forward(
        self,
        branch_input: torch.Tensor,
        trunk_input: torch.Tensor,
    ) -> torch.Tensor:
        """Predict normalized velocity."""
        branch_output = self.branch_net(branch_input)
        trunk_output = self.trunk_net(trunk_input)

        output = torch.sum(branch_output * trunk_output, dim=1, keepdim=True)
        output = output + self.bias

        return output


def sample_training_batch(
    rng: np.random.Generator,
    train_indices: np.ndarray,
    branch_features: np.ndarray,
    velocity_fields: np.ndarray,
    z: np.ndarray,
    eta: np.ndarray,
    batch_size: int,
    branch_mean: np.ndarray,
    branch_std: np.ndarray,
    target_mean: float,
    target_std: float,
    device: torch.device,
):
    """Sample a random pointwise training batch."""
    sample_indices = rng.choice(train_indices, size=batch_size, replace=True)

    n_z = len(z)
    n_eta = len(eta)

    z_indices = rng.integers(0, n_z, size=batch_size)
    eta_indices = rng.integers(0, n_eta, size=batch_size)

    branch_batch = branch_features[sample_indices]
    branch_batch = (branch_batch - branch_mean) / branch_std

    trunk_batch = np.stack(
        [
            z[z_indices],
            eta[eta_indices],
        ],
        axis=1,
    ).astype(np.float32)

    target_batch = velocity_fields[
        sample_indices,
        z_indices,
        eta_indices,
    ].astype(np.float32)[:, None]

    target_batch = (target_batch - target_mean) / target_std

    branch_tensor = torch.tensor(
        branch_batch,
        dtype=torch.float32,
        device=device,
    )

    trunk_tensor = torch.tensor(
        trunk_batch,
        dtype=torch.float32,
        device=device,
    )

    target_tensor = torch.tensor(
        target_batch,
        dtype=torch.float32,
        device=device,
    )

    return branch_tensor, trunk_tensor, target_tensor


@torch.no_grad()
def evaluate_pointwise_loss(
    model: nn.Module,
    rng: np.random.Generator,
    val_indices: np.ndarray,
    branch_features: np.ndarray,
    velocity_fields: np.ndarray,
    z: np.ndarray,
    eta: np.ndarray,
    batch_size: int,
    branch_mean: np.ndarray,
    branch_std: np.ndarray,
    target_mean: float,
    target_std: float,
    device: torch.device,
) -> float:
    """Evaluate validation MSE on random point samples."""
    model.eval()

    branch_tensor, trunk_tensor, target_tensor = sample_training_batch(
        rng=rng,
        train_indices=val_indices,
        branch_features=branch_features,
        velocity_fields=velocity_fields,
        z=z,
        eta=eta,
        batch_size=batch_size,
        branch_mean=branch_mean,
        branch_std=branch_std,
        target_mean=target_mean,
        target_std=target_std,
        device=device,
    )

    prediction = model(branch_tensor, trunk_tensor)
    loss = torch.mean((prediction - target_tensor) ** 2)

    return float(loss.detach().cpu().item())


@torch.no_grad()
def predict_full_field(
    model: nn.Module,
    branch_feature: np.ndarray,
    z: np.ndarray,
    eta: np.ndarray,
    branch_mean: np.ndarray,
    branch_std: np.ndarray,
    target_mean: float,
    target_std: float,
    device: torch.device,
    chunk_size: int = 8192,
) -> np.ndarray:
    """Predict the full u(z, eta) field for one sample."""
    model.eval()

    z_grid, eta_grid = np.meshgrid(z, eta, indexing="ij")
    coords = np.stack(
        [
            z_grid.reshape(-1),
            eta_grid.reshape(-1),
        ],
        axis=1,
    ).astype(np.float32)

    branch_normalized = (branch_feature[None, :] - branch_mean) / branch_std
    branch_repeated = np.repeat(branch_normalized, coords.shape[0], axis=0)

    predictions = []

    for start in range(0, coords.shape[0], chunk_size):
        end = start + chunk_size

        branch_tensor = torch.tensor(
            branch_repeated[start:end],
            dtype=torch.float32,
            device=device,
        )

        trunk_tensor = torch.tensor(
            coords[start:end],
            dtype=torch.float32,
            device=device,
        )

        pred = model(branch_tensor, trunk_tensor)
        pred = pred.detach().cpu().numpy()

        predictions.append(pred)

    prediction = np.concatenate(predictions, axis=0).reshape(len(z), len(eta))
    prediction = prediction * target_std + target_mean

    return prediction


def plot_training_history(
    train_losses,
    val_losses,
    output_path: Path,
) -> None:
    """Plot training and validation loss curves."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(7, 4.5), constrained_layout=True)

    ax.semilogy(train_losses, label="Train loss")
    ax.semilogy(val_losses, label="Validation loss")

    ax.set_xlabel("Epoch")
    ax.set_ylabel("MSE loss")
    ax.set_title("DeepONet forward-operator training")
    ax.legend()

    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    print(f"Saved: {output_path}")


def plot_prediction_example(
    model: nn.Module,
    sample_idx: int,
    branch_features: np.ndarray,
    velocity_fields: np.ndarray,
    z: np.ndarray,
    eta: np.ndarray,
    branch_mean: np.ndarray,
    branch_std: np.ndarray,
    target_mean: float,
    target_std: float,
    device: torch.device,
    output_path: Path,
) -> float:
    """Plot target, prediction, and absolute error for one validation sample."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    target = velocity_fields[sample_idx]
    prediction = predict_full_field(
        model=model,
        branch_feature=branch_features[sample_idx],
        z=z,
        eta=eta,
        branch_mean=branch_mean,
        branch_std=branch_std,
        target_mean=target_mean,
        target_std=target_std,
        device=device,
    )

    error = np.abs(prediction - target)

    relative_l2 = np.linalg.norm(prediction - target) / np.linalg.norm(target)

    z_grid, eta_grid = np.meshgrid(z, eta, indexing="ij")

    vmax = max(float(target.max()), float(prediction.max()))

    fig, axes = plt.subplots(
        1,
        3,
        figsize=(13, 3.8),
        constrained_layout=True,
    )

    panels = [
        ("Target", target, 0.0, vmax),
        ("Prediction", prediction, 0.0, vmax),
        ("Absolute error", error, 0.0, float(error.max())),
    ]

    for ax, (title, field, vmin, vmax_panel) in zip(axes, panels):
        contour = ax.contourf(
            z_grid,
            eta_grid,
            field,
            levels=50,
            vmin=vmin,
            vmax=vmax_panel,
        )

        ax.set_title(title)
        ax.set_xlabel(r"$z/L$")
        ax.set_ylabel(r"$\eta = r/R(z)$")
        ax.set_xlim(0.0, 1.0)
        ax.set_ylim(0.0, 1.0)

        fig.colorbar(contour, ax=ax, shrink=0.9)

    fig.suptitle(
        f"DeepONet prediction example | sample {sample_idx} | "
        f"relative L2 = {relative_l2:.3e}",
        fontsize=12,
    )

    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    print(f"Saved: {output_path}")
    print(f"Example relative L2 error: {relative_l2:.6e}")

    return float(relative_l2)


def parse_args():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Train a DeepONet baseline on the forward-operator dataset."
    )

    parser.add_argument(
        "--dataset",
        type=str,
        default="data/forward_operator_dataset.npz",
        help="Path to the generated dataset.",
    )

    parser.add_argument(
        "--epochs",
        type=int,
        default=500,
        help="Number of training epochs.",
    )

    parser.add_argument(
        "--batch-size",
        type=int,
        default=4096,
        help="Number of random coordinate samples per batch.",
    )

    parser.add_argument(
        "--hidden-dim",
        type=int,
        default=128,
        help="Hidden width of branch and trunk networks.",
    )

    parser.add_argument(
        "--latent-dim",
        type=int,
        default=128,
        help="Latent dimension for branch/trunk dot product.",
    )

    parser.add_argument(
        "--n-layers",
        type=int,
        default=3,
        help="Number of hidden layers in branch and trunk networks.",
    )

    parser.add_argument(
        "--learning-rate",
        type=float,
        default=1e-3,
        help="Adam learning rate.",
    )

    parser.add_argument(
        "--val-fraction",
        type=float,
        default=0.2,
        help="Validation fraction.",
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=123,
        help="Random seed.",
    )

    return parser.parse_args()


def main() -> None:
    """Train the DeepONet baseline."""
    args = parse_args()

    torch.manual_seed(args.seed)
    rng = np.random.default_rng(args.seed)

    device = get_device()
    print(f"Using device: {device}")

    data = load_dataset(Path(args.dataset))

    z = data["z"].astype(np.float32)
    eta = data["eta"].astype(np.float32)
    velocity_fields = data["velocity_fields"].astype(np.float32)

    branch_features = build_branch_features(data)

    n_samples = branch_features.shape[0]
    train_indices, val_indices = train_val_split(
        n_samples=n_samples,
        val_fraction=args.val_fraction,
        seed=args.seed,
    )

    branch_mean = branch_features[train_indices].mean(axis=0, keepdims=True)
    branch_std = branch_features[train_indices].std(axis=0, keepdims=True)
    branch_std = np.where(branch_std < 1e-8, 1.0, branch_std)

    train_targets = velocity_fields[train_indices]
    target_mean = float(train_targets.mean())
    target_std = float(train_targets.std())
    if target_std < 1e-8:
        target_std = 1.0

    print(f"Number of samples: {n_samples}")
    print(f"Train samples:     {len(train_indices)}")
    print(f"Validation samples:{len(val_indices)}")
    print(f"Branch dimension:  {branch_features.shape[1]}")
    print(f"Target mean/std:   {target_mean:.6e} / {target_std:.6e}")

    model = DeepONet(
        branch_dim=branch_features.shape[1],
        trunk_dim=2,
        latent_dim=args.latent_dim,
        hidden_dim=args.hidden_dim,
        n_layers=args.n_layers,
    ).to(device)

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=args.learning_rate,
    )

    train_losses = []
    val_losses = []

    for epoch in range(1, args.epochs + 1):
        model.train()

        branch_tensor, trunk_tensor, target_tensor = sample_training_batch(
            rng=rng,
            train_indices=train_indices,
            branch_features=branch_features,
            velocity_fields=velocity_fields,
            z=z,
            eta=eta,
            batch_size=args.batch_size,
            branch_mean=branch_mean,
            branch_std=branch_std,
            target_mean=target_mean,
            target_std=target_std,
            device=device,
        )

        optimizer.zero_grad()
        prediction = model(branch_tensor, trunk_tensor)
        loss = torch.mean((prediction - target_tensor) ** 2)
        loss.backward()
        optimizer.step()

        train_loss = float(loss.detach().cpu().item())

        val_loss = evaluate_pointwise_loss(
            model=model,
            rng=rng,
            val_indices=val_indices,
            branch_features=branch_features,
            velocity_fields=velocity_fields,
            z=z,
            eta=eta,
            batch_size=args.batch_size,
            branch_mean=branch_mean,
            branch_std=branch_std,
            target_mean=target_mean,
            target_std=target_std,
            device=device,
        )

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        if epoch == 1 or epoch % 25 == 0 or epoch == args.epochs:
            print(
                f"Epoch {epoch:05d} | "
                f"train MSE = {train_loss:.6e} | "
                f"val MSE = {val_loss:.6e}"
            )

    model_dir = Path("models")
    model_dir.mkdir(exist_ok=True)

    model_path = model_dir / "deeponet_forward_baseline.pt"

    torch.save(
        {
            "model_state_dict": model.state_dict(),
            "branch_mean": branch_mean,
            "branch_std": branch_std,
            "target_mean": target_mean,
            "target_std": target_std,
            "branch_dim": branch_features.shape[1],
            "latent_dim": args.latent_dim,
            "hidden_dim": args.hidden_dim,
            "n_layers": args.n_layers,
            "z": z,
            "eta": eta,
        },
        model_path,
    )

    print(f"Saved model: {model_path}")

    plot_training_history(
        train_losses=train_losses,
        val_losses=val_losses,
        output_path=Path("figures/deeponet_forward_training_loss.png"),
    )

    example_sample_idx = int(val_indices[0])

    plot_prediction_example(
        model=model,
        sample_idx=example_sample_idx,
        branch_features=branch_features,
        velocity_fields=velocity_fields,
        z=z,
        eta=eta,
        branch_mean=branch_mean,
        branch_std=branch_std,
        target_mean=target_mean,
        target_std=target_std,
        device=device,
        output_path=Path("figures/deeponet_forward_prediction_example.png"),
    )


if __name__ == "__main__":
    main()
